### ISSUE TITLE
TODOアプリの目的とタスク

### ISSUE THREAD

**Issue by haruka-mura** [haruka-mura/todo-app#1]
# 目的
ToDo ソフトでは、
- 期日を設定できるが、いつやるのかがわからない
- 同じことを達成しようとしているグループの人が、今日やる予定がわからない

なので
- 自分の今日やることがわかる
- グループの人の今日やることがわかる
- これからの予定がわかる / 決められる

以上を実現するようなTODOアプリケーションを作る

[▼詳細はここ▼](https://mwed.esa.io/posts/13771)

## 必要なタスク
![img_20180605_155024](https://user-images.githubusercontent.com/25021777/40962354-3c6a5b16-68e0-11e8-9766-8c2b055c7584.jpg)
- [x]  テーブル設計
- [x] Railsプロジェクトの新規作成&設定
- [x] ルーティング設計
- [x] 必要なモデルの作成
- [x] トップページを作る
- [x] IDとパスワードでユーザー登録できるようにする
- [x] ユーザーがログインできる
- [x] ユーザーがログアウトできる
- [x] ユーザーがグループを新規作成できる
- [ ] ユーザーがタスクを登録できる
- [x] ユーザーがタスク一覧を見られる
- [ ] ”いまやる”一覧を見れる
- [ ] ”後でやる”一覧を見れる
- [ ] ”いつかやる”一覧を見れる
- [x] ユーザーはタスク詳細ページを見れる
- [ ] ユーザーがタスクを編集できる
- [ ] ユーザーはグループ詳細が見れて、終わった/終わってないタスクの数がわかる
- [ ] ユーザーが所属するグループの一覧が見れる
- [ ] ユーザーがグループ一覧を見れる
- [ ] ユーザーが他のグループにJOINできる
- [ ] ユーザーが登録しているユーザーの一覧を見られる
- [ ] ユーザーがグループに他のユーザーをINVITEできる
- [ ] ユーザーがグループから退出できる

### PLUS
- 期日が過ぎたけどDONEしてないタスクのアラートをだす

**Comment by matsuhisa** [comment]
できたのは チェックしたいね

**Comment by haruka-mura** [comment]
パイロットプロジェクト終わってるのでクローズ
