### ISSUE TITLE
ルーティングの案

### ISSUE THREAD

**Issue by haruka-mura** [haruka-mura/todo-app#3]
## 第一回ルーティング案6/6
すでにセッション情報を持っているユーザーがルートにアクセスしたら
/users/idへリダイレクトしてあげる👀

| 表示内容 | ルーティング |
| ---- | ---- |
| トップ | / |
| 新規登録 |/users/new  |
|ログイン|/sessions/new|
|ユーザーページ|/users/id|
|todo登録|/todos/new|
|todo一覧|/todos|
|todo詳細|/todos/id|
|グループ登録|/teams/new|
|グループ一覧|/teams|
|グループ詳細|/teams/id|

**Comment by YasukeXXX** [comment]
テーブル名tasksならリソースもtasksのほうがよくない？
グループもgroupかteamどっちかに統一したい。

`/todos` では自分の担当するタスクが表示される感じ？
将来的に他の人が担当するタスクの一覧を見たくなったらどういうルーティングになるかちょっと考えてみてほしい。

タスクの登録はグループの詳細ページからするんだったような気がするんだけど、それならurlからグループのidが分かっていた方が自然かもしれない。(たとえば`/teams/:team_id/todos/new`)

それからタスクとグループのedit, updateが足りてないね。ログアウトも。

**Comment by haruka-mura** [comment]
| 表示内容 || ルーティング |
| ---- | ---- | ---- |
| トップ || / |
| 新規登録 |GET|/users/new |
||POST|/users|
|ログイン|GET|/sessions/new|
||POST|/sessions|
|ログアウト|DELETE|/sessions|
|ユーザータスク一覧（ユーザーページ）|GET|/users/:id|
|タスク登録|GET|/teams/:team_id/tasks/new|
||POST|/teams/:team_id/tasks|
|タスク編集|GET|/teams/:team_id/tasks/:id/edit|
||PATCH|/teams/:team_id/tasks/:id|
|グループのタスク一覧|GET|/teams/:team_id/tasks|
|タスク詳細|GET|/teams/:team_id/tasks/:id|
|グループ登録|GET|/teams/new|
||POST|/teams|
|グループ編集|GET|/teams/:id/edit|
||PATCH|/teams/:id|
|グループ一覧|GET|/teams|
|グループ詳細|GET|/teams/:id|

**Comment by haruka-mura** [comment]
@YasukeXXX 確認お願いしますっ

**Comment by haruka-mura** [comment]
うーん、こうかな...
| 表示内容 || ルーティング ||
| ---- | ---- | ---- | ---- |
|ユーザーページ(plofile)|GET|/users/:id||
|ユーザーページ(tasks)|GET|/users/:id/tasks||

**Comment by haruka-mura** [comment]
- taskはグループの変更をすることがある
- taskの登録はユーザーページからも、グループのページからもできる（とべんり）
- /users/:id, /teams/:id はマイページ的な
- タスクとチームは独立している
- あくまでもタスクがメイン
- グループはタスクをあくまで、くくるためのもの！

**Comment by haruka-mura** [comment]
| 表示内容 || ルーティング ||
| ---- | ---- | ---- | ---- |
| トップ || / ||
| 新規登録 |GET|/users/new |/signup|
||POST|/users||
|ログイン|GET|/sessions/new|/login|
||POST|/sessions||
|ログアウト|DELETE|/sessions||
|ユーザー一覧|GET|/users||
|ユーザータスク一覧（ユーザーページ）|GET|/users/:id||
|タスク登録|GET|/tasks/new||
||POST|/tasks||
|タスク編集|GET|/tasks/:id/edit||
||PATCH|/tasks/:id||
|グループのタスク一覧|GET|/teams/:team_id/tasks||
|タスク詳細|GET|/tasks/:id||
|グループ登録|GET|/teams/new||
||POST|/teams||
|グループ編集|GET|/teams/:id/edit||
||PATCH|/teams/:id||
|グループ一覧|GET|/teams||
|グループ詳細|GET|/teams/:id||

**Comment by YasukeXXX** [comment]
おーけー

**Comment by haruka-mura** [comment]
これもクローズ
